// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCiliumBGPVirtualRouters implements CiliumBGPVirtualRouterInterface
type FakeCiliumBGPVirtualRouters struct {
	Fake *FakeCiliumV2alpha1
}

var ciliumbgpvirtualroutersResource = schema.GroupVersionResource{Group: "cilium.io", Version: "v2alpha1", Resource: "ciliumbgpvirtualrouters"}

var ciliumbgpvirtualroutersKind = schema.GroupVersionKind{Group: "cilium.io", Version: "v2alpha1", Kind: "CiliumBGPVirtualRouter"}

// Get takes name of the ciliumBGPVirtualRouter, and returns the corresponding ciliumBGPVirtualRouter object, and an error if there is any.
func (c *FakeCiliumBGPVirtualRouters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(ciliumbgpvirtualroutersResource, name), &v2alpha1.CiliumBGPVirtualRouter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), err
}

// List takes label and field selectors, and returns the list of CiliumBGPVirtualRouters that match those selectors.
func (c *FakeCiliumBGPVirtualRouters) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumBGPVirtualRouterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(ciliumbgpvirtualroutersResource, ciliumbgpvirtualroutersKind, opts), &v2alpha1.CiliumBGPVirtualRouterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.CiliumBGPVirtualRouterList{ListMeta: obj.(*v2alpha1.CiliumBGPVirtualRouterList).ListMeta}
	for _, item := range obj.(*v2alpha1.CiliumBGPVirtualRouterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ciliumBGPVirtualRouters.
func (c *FakeCiliumBGPVirtualRouters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(ciliumbgpvirtualroutersResource, opts))
}

// Create takes the representation of a ciliumBGPVirtualRouter and creates it.  Returns the server's representation of the ciliumBGPVirtualRouter, and an error, if there is any.
func (c *FakeCiliumBGPVirtualRouters) Create(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.CreateOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(ciliumbgpvirtualroutersResource, ciliumBGPVirtualRouter), &v2alpha1.CiliumBGPVirtualRouter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), err
}

// Update takes the representation of a ciliumBGPVirtualRouter and updates it. Returns the server's representation of the ciliumBGPVirtualRouter, and an error, if there is any.
func (c *FakeCiliumBGPVirtualRouters) Update(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(ciliumbgpvirtualroutersResource, ciliumBGPVirtualRouter), &v2alpha1.CiliumBGPVirtualRouter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCiliumBGPVirtualRouters) UpdateStatus(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (*v2alpha1.CiliumBGPVirtualRouter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(ciliumbgpvirtualroutersResource, "status", ciliumBGPVirtualRouter), &v2alpha1.CiliumBGPVirtualRouter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), err
}

// Delete takes name of the ciliumBGPVirtualRouter and deletes it. Returns an error if one occurs.
func (c *FakeCiliumBGPVirtualRouters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(ciliumbgpvirtualroutersResource, name, opts), &v2alpha1.CiliumBGPVirtualRouter{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCiliumBGPVirtualRouters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(ciliumbgpvirtualroutersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.CiliumBGPVirtualRouterList{})
	return err
}

// Patch applies the patch and returns the patched ciliumBGPVirtualRouter.
func (c *FakeCiliumBGPVirtualRouters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(ciliumbgpvirtualroutersResource, name, pt, data, subresources...), &v2alpha1.CiliumBGPVirtualRouter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), err
}
