// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CiliumBGPVirtualRoutersGetter has a method to return a CiliumBGPVirtualRouterInterface.
// A group's client should implement this interface.
type CiliumBGPVirtualRoutersGetter interface {
	CiliumBGPVirtualRouters() CiliumBGPVirtualRouterInterface
}

// CiliumBGPVirtualRouterInterface has methods to work with CiliumBGPVirtualRouter resources.
type CiliumBGPVirtualRouterInterface interface {
	Create(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.CreateOptions) (*v2alpha1.CiliumBGPVirtualRouter, error)
	Update(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (*v2alpha1.CiliumBGPVirtualRouter, error)
	UpdateStatus(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (*v2alpha1.CiliumBGPVirtualRouter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.CiliumBGPVirtualRouter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.CiliumBGPVirtualRouterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumBGPVirtualRouter, err error)
	CiliumBGPVirtualRouterExpansion
}

// ciliumBGPVirtualRouters implements CiliumBGPVirtualRouterInterface
type ciliumBGPVirtualRouters struct {
	client rest.Interface
}

// newCiliumBGPVirtualRouters returns a CiliumBGPVirtualRouters
func newCiliumBGPVirtualRouters(c *CiliumV2alpha1Client) *ciliumBGPVirtualRouters {
	return &ciliumBGPVirtualRouters{
		client: c.RESTClient(),
	}
}

// Get takes name of the ciliumBGPVirtualRouter, and returns the corresponding ciliumBGPVirtualRouter object, and an error if there is any.
func (c *ciliumBGPVirtualRouters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	result = &v2alpha1.CiliumBGPVirtualRouter{}
	err = c.client.Get().
		Resource("ciliumbgpvirtualrouters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CiliumBGPVirtualRouters that match those selectors.
func (c *ciliumBGPVirtualRouters) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumBGPVirtualRouterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.CiliumBGPVirtualRouterList{}
	err = c.client.Get().
		Resource("ciliumbgpvirtualrouters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ciliumBGPVirtualRouters.
func (c *ciliumBGPVirtualRouters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("ciliumbgpvirtualrouters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ciliumBGPVirtualRouter and creates it.  Returns the server's representation of the ciliumBGPVirtualRouter, and an error, if there is any.
func (c *ciliumBGPVirtualRouters) Create(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.CreateOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	result = &v2alpha1.CiliumBGPVirtualRouter{}
	err = c.client.Post().
		Resource("ciliumbgpvirtualrouters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumBGPVirtualRouter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ciliumBGPVirtualRouter and updates it. Returns the server's representation of the ciliumBGPVirtualRouter, and an error, if there is any.
func (c *ciliumBGPVirtualRouters) Update(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	result = &v2alpha1.CiliumBGPVirtualRouter{}
	err = c.client.Put().
		Resource("ciliumbgpvirtualrouters").
		Name(ciliumBGPVirtualRouter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumBGPVirtualRouter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ciliumBGPVirtualRouters) UpdateStatus(ctx context.Context, ciliumBGPVirtualRouter *v2alpha1.CiliumBGPVirtualRouter, opts v1.UpdateOptions) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	result = &v2alpha1.CiliumBGPVirtualRouter{}
	err = c.client.Put().
		Resource("ciliumbgpvirtualrouters").
		Name(ciliumBGPVirtualRouter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumBGPVirtualRouter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ciliumBGPVirtualRouter and deletes it. Returns an error if one occurs.
func (c *ciliumBGPVirtualRouters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("ciliumbgpvirtualrouters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ciliumBGPVirtualRouters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("ciliumbgpvirtualrouters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ciliumBGPVirtualRouter.
func (c *ciliumBGPVirtualRouters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumBGPVirtualRouter, err error) {
	result = &v2alpha1.CiliumBGPVirtualRouter{}
	err = c.client.Patch(pt).
		Resource("ciliumbgpvirtualrouters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
