// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumBGPVirtualRouterLister helps list CiliumBGPVirtualRouters.
// All objects returned here must be treated as read-only.
type CiliumBGPVirtualRouterLister interface {
	// List lists all CiliumBGPVirtualRouters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumBGPVirtualRouter, err error)
	// Get retrieves the CiliumBGPVirtualRouter from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumBGPVirtualRouter, error)
	CiliumBGPVirtualRouterListerExpansion
}

// ciliumBGPVirtualRouterLister implements the CiliumBGPVirtualRouterLister interface.
type ciliumBGPVirtualRouterLister struct {
	indexer cache.Indexer
}

// NewCiliumBGPVirtualRouterLister returns a new CiliumBGPVirtualRouterLister.
func NewCiliumBGPVirtualRouterLister(indexer cache.Indexer) CiliumBGPVirtualRouterLister {
	return &ciliumBGPVirtualRouterLister{indexer: indexer}
}

// List lists all CiliumBGPVirtualRouters in the indexer.
func (s *ciliumBGPVirtualRouterLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumBGPVirtualRouter, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumBGPVirtualRouter))
	})
	return ret, err
}

// Get retrieves the CiliumBGPVirtualRouter from the index for a given name.
func (s *ciliumBGPVirtualRouterLister) Get(name string) (*v2alpha1.CiliumBGPVirtualRouter, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumbgpvirtualrouter"), name)
	}
	return obj.(*v2alpha1.CiliumBGPVirtualRouter), nil
}
