package main

import (
	"bytes"
	"text/template"
	"unicode"

	"github.com/cilium/ebpf"
)

var mapSpecTpl = `// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package {{ .Package }}

import (
	"bytes"
	_ "embed"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/btf"
)

//go:embed maps.btf
var mapBtf []byte

func LoadMapSpecs() (map[string]*ebpf.MapSpec, error) {
	btfSpec, err := btf.LoadSpecFromReader(bytes.NewReader(mapBtf))
	if err != nil {
		return nil, err
	}

	mapSpecs := make(map[string]*ebpf.MapSpec)
	for _, constructor := range constructors {
		spec, err := constructor(btfSpec)
		if err != nil {
			return nil, err
		}
		mapSpecs[spec.Name] = spec
	}

	return mapSpecs, nil
}

type constructor func(btf *btf.Spec) (*ebpf.MapSpec, error)

var constructors []constructor = []constructor{
{{- range .OuterMaps }}
	new{{ camelCase .Name }}Spec,
{{- end }}
}
{{ range .Maps }}
func new{{ camelCase .Name }}Spec(btf *btf.Spec) (*ebpf.MapSpec, error) {
	spec := &ebpf.MapSpec{
		Name:       "{{ .Name }}",
		Type:       ebpf.{{ .Type.String }},
		KeySize:    {{ .KeySize }},
		ValueSize:  {{ .ValueSize }},
		MaxEntries: {{ .MaxEntries }},
		Flags:      {{ .Flags }},
		Pinning:    ebpf.{{ .Pinning.String }},
	}

	var err error{{ if .Key }}
	spec.Key, err = btf.AnyTypeByName("{{ .Key.TypeName }}")
	if err != nil {
		return nil, fmt.Errorf("getting key type for map %s: %w", spec.Name, err)
	}{{ end }}{{ if .Value }}

	spec.Value, err = btf.AnyTypeByName("{{ .Value.TypeName }}")
	if err != nil {
		return nil, fmt.Errorf("getting value type for map %s: %w", spec.Name, err)
	}{{ end }}{{ if .InnerMap }}

	spec.InnerMap, err = new{{ camelCase .InnerMap.Name }}Spec(btf)
	if err != nil {
		return nil, fmt.Errorf("getting inner map spec for map %s: %w", spec.Name, err)
	}{{ end }}

	return spec, err
}
{{ end }}`

type mapSpecProxy struct {
	*ebpf.MapSpec
}

func renderMapSpecs(outerSpecs, combinedSpecs []*ebpf.MapSpec, pkg string) (string, error) {
	var err error
	tpl := template.New("mapSpec")
	tpl.Funcs(map[string]any{
		"camelCase": func(s string) string {
			var result string
			capNext := true
			for _, r := range s {
				if r == '_' || r == '.' {
					capNext = true
					continue
				}
				if capNext {
					result += string(unicode.ToUpper(r))
					capNext = false
				} else {
					result += string(r)
				}
			}
			return result
		},
	})
	tpl, err = tpl.Parse(mapSpecTpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err = tpl.Execute(&buf, struct {
		Package   string
		OuterMaps []*ebpf.MapSpec
		Maps      []*ebpf.MapSpec
	}{
		Package:   pkg,
		OuterMaps: outerSpecs,
		Maps:      combinedSpecs,
	}); err != nil {
		return "", err
	}

	return buf.String(), nil
}
